### ISSUE TITLE
"OUT" Node not useable anymore with Deconz 2.3.6 on Safari

### ISSUE THREAD

**Issue by EdStark666** [deconz-community/node-red-contrib-deconz#217] opened 2022-10-13 16:43 UTC
### Current Behavior

"OUT" Node has a bug which leads to the situation, that no commands can be set. Because of that, devices cant be controlled anymore with Deconz in Nodered.

### Expected Behavior

Add commands in the OUT node like before.

### Steps To Reproduce

Create OUT Node in Nodered and try to add homekit or state or config or custom command.

### Example flow

```json
paste your flow here
```

### Environment

- deCONZ plugin version: 2.3.6
- HomeKit plugin version (if used):
- Node-RED version: 3.0.2
- Node.js version:
- npm version:
- Platform/OS: RaspberryPi3
- Browser: Safari

**Comment by EdStark666** [comment] 2022-10-13 16:46
Seems to be a safari problem. Works on chrome browser as before.

**Comment by Zehir** [comment] 2022-10-13 18:10
What version of Safari are you using ?

**Comment by EdStark666** [comment] 2022-10-13 18:35
Safari 16.0 on macOS 12.6 Monterey (newest SW). 
Screenshot of issue: [https://im.ge/i/2sjsLz](url)
Yes, there are errors, screenshot [https://im.ge/i/2sjqTS](url)

**Comment by Zehir** [comment] 2022-10-13 18:54
This can't help me, I will try to install safari on windows later

**Comment by Zehir** [comment] 2022-10-15 12:07
I tried on a new node using a safari from a virtual machine and I can't reproduce the issue. Could you come over discord to talk about that issue ? I ping you [here](https://discord.com/channels/494922323518947329/1030807349365063820/1030807351760015371).

**Comment by dionmes** [comment] 2022-11-06 12:15
I got the same issue. The specifics option section and commands section do not expand or are populated under safari on MacOS. This is the first time I try this out, thought I did something wrong but then saw this thread.

Safari Version 16.1 (18614.2.9.1.12)

**Comment by fuzzy01** [comment] 2022-12-10 14:25
I have the same issue on MacOS. Very annoying.

Safari Version 16.1 (18614.2.9.1.12)
MacOS Ventura 13.0.1

**Comment by raddi** [comment] 2022-12-11 17:45
Same issue on macOS Ventura 13.0.1 and Safari 16.1 - The Commands tab seems to be empty, but in Chrome it does work, so there may are some display issues in safari?
<img width="514" alt="Bildschirm­foto 2022-12-11 um 18 43 23" src="https://user-images.githubusercontent.com/9991431/206919717-ee1b8be2-9c3c-410d-b73c-509e444ac91d.png">

**Comment by Zehir** [comment] 2022-12-11 18:55
I have no idea why this don't work on safari and I can't reproduce on my side. Somebody can come on discord to debug this in real time ?

**Comment by Zehir** [comment] 2022-12-20 20:44
Does this happen on ipad too ?

**Comment by dionmes** [comment] 2022-12-20 21:19
I can confirm this happens on iPad too and also in Chrome on the iPad (which makes sense).

**Comment by Zehir** [comment] 2022-12-21 16:58
For some reason doing this fix the issue : 
```javascript
  async generateTypedInput(container, options, stupidFix = "safari") {
    console.log("Stupid fix for " + stupidFix);
```
By adding an new param and doing something with it like print in the console it's fix.
The issue is that the options value became undefined but it defined when the method is called. I don't understand what is happening here.

I looking for a better fix

**Comment by Zehir** [comment] 2022-12-21 17:38
Released in 2.3.7

**Comment by dionmes** [comment] 2022-12-21 18:16
Sounds good, but in NR I can already upgrade to 2.3.8.

**Comment by Automayted** [comment] 2022-12-28 05:08
I'm seeing a very similar issue in macOS 12.6.1 with Safari 16.2 running v2.3.8.

Safari shows a mix of light and cover parameters, notably missing transition time:
![Screen Shot 2022-12-27 at 11 05 08 PM](https://user-images.githubusercontent.com/66129101/209760419-0c3d6cf1-9317-41ec-973b-c2affddcac3e.png)

Chrome shows everything correctly:
![Screen Shot 2022-12-27 at 11 05 15 PM](https://user-images.githubusercontent.com/66129101/209760490-d9b018f1-b26f-4acd-a2c2-146cd9379fa6.png)

I've cleared all Safari cache, rebooted, all with no change.

Am I overlooking something obvious, or is there still an issue with Safari in v2.3.8?

**Comment by Zehir** [comment] 2022-12-28 06:57
Damned safari

**Comment by Automayted** [comment] 2022-12-29 15:58
> Damned safari

Ha. Let me know if I can offer any assistance with logs or whatnot. Thanks for all your efforts on this project!

**Comment by Zehir** [comment] 2022-12-30 10:53
> > Damned safari
> 
> Ha. Let me know if I can offer any assistance with logs or whatnot. Thanks for all your efforts on this project!

Yes could you check on the browser console if there is any errors ?

**Comment by Automayted** [comment] 2022-12-30 13:59
> > > Damned safari
> > 
> > 
> > Ha. Let me know if I can offer any assistance with logs or whatnot. Thanks for all your efforts on this project!
> 
> Yes could you check on the browser console if there is any errors ?

I get this one each time I open a deCONZ OUT node:

`[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'container.append')
	(anonymous function) (deconz-editor.js:1:41856)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob`

**Comment by Zehir** [comment] 2022-12-30 14:00
Ok I see it's the same safari bug where object became undefined by magic, I will work on a fix this weekend

**Closed** 2023-01-04 21:43 UTC
Labels: bug

**Comment by Zehir** [comment] 2023-01-04 22:49
Was related to https://github.com/mishoo/UglifyJS/issues/5155
