### ISSUE TITLE
Missing parameter in OUT-node 

### ISSUE THREAD

**Issue by Nooblucker1** [deconz-community/node-red-contrib-deconz#219] opened 2022-11-05 08:45 UTC
### Current Behavior

As you can see in the print screen, in the out node is the server avaiable, I can select a light but both fields: Specific options and commands are empty. So I am not able to setup a light, sensors are working properly in the in node. 

<img width="1392" alt="Bildschirm­foto 2022-11-05 um 09 34 30" src="https://user-images.githubusercontent.com/46654726/200111566-6e1a0035-51f3-4464-8860-5301c5288131.png">

### Expected Behavior

I expect that both fields: specific options and commands have the possibility to set up parameters.

### Example flow

```json
paste your flow here
```

### Environment

My system, Synology NAS docker version red node 3.0.2 and the newest deconz 2.3.6.

**Comment by Zehir** [comment] 2022-11-05 09:01
Are you using Safari ?

**Comment by Nooblucker1** [comment] 2022-11-05 09:05
Thx for your quick reply.
Yes, I try it with FireFox and it works now :-) So its a bug in combination with Safari, will this fixed?
You made my day!

**Comment by Zehir** [comment] 2022-11-05 09:08
I hope but I was not able to reproduce. I tried à mac emulator but dont get the issue there. If you could come on the discord to debug that i  réal time in a few days

**Comment by Zehir** [comment] 2022-11-05 09:09
Duplicate of #217

**Closed by Zehir** 2022-11-05 09:09 UTC
